# frozen_string_literal: true

namespace :tailwind do
  desc "Write Tailwind @source paths for bundled FlatPack and Recording Studio gems"
  task bundle_sources: :environment do
    gems = {
      "flat_pack" => %w[app/components/**/*.rb app/components/**/*.erb],
      "recording_studio" => %w[app/views/**/*.erb],
      "recording_studio_root_switchable" => %w[app/views/**/*.erb app/helpers/**/*.rb],
      "recording_studio_orderable" => %w[app/views/**/*.erb],
      "recording_studio_trashable" => %w[app/views/**/*.erb],
      "recording_studio_duplicatable" => %w[app/views/**/*.erb]
    }

    lines = [ "/* Generated by rake tailwind:bundle_sources. Do not edit. */" ]

    gems.each do |gem_name, globs|
      spec = Bundler.rubygems.find_name(gem_name).first
      raise "Missing gem #{gem_name} for Tailwind sources" if spec.nil?

      globs.each do |glob|
        lines << %(@source "#{File.join(spec.full_gem_path, glob)}";)
      end
    end

    Rails.root.join("app/assets/tailwind/bundle_sources.css").write("#{lines.join("\n")}\n")
  end
end

Rake::Task["tailwindcss:build"].enhance([ "tailwind:bundle_sources" ])
Rake::Task["tailwindcss:watch"].enhance([ "tailwind:bundle_sources" ])
